feat: 전화번호 sms 인증
avalon-202n/avalon-chat-backend pull request #59
Opened 2023-04-12 06:29 UTC by hgene0929

## Summary

*전화번호 인증 구현
*SMS 전송 API 구현을 위해 [CoolSMS](https://coolsms.co.kr/)를 사용하였습니다.

## (Optional): Description

*전화번호는 프로필 필드이지만, 인증기능을 위한 도메인,서비스,레포지토리,외부API도 필요한 것을 고려하여 "인증"도메인을 분리하였습니다.
*조금 걸리는 부분은 제가 사용한 url,변수명 등이 RESTful한가에 대한 부분입니다..

## How Has This Been Tested?

*문자 전송 기능, 인증번호 전송, 인증코드 검증 3가지 서비스 코드에 대한 테스트를 진행하였습니다.

2023-04-12 07:09 UTC, ndy2 requested changes
`UserServiceImpl` 와 `SignUpController` 를 확인해주세요. T.T

2023-04-12 07:09 UTC, ndy2 commented on src/main/java/com/avalon/avalonchat/domain/auth/domain/AuthPhoneNumber.java
> +	private boolean isValidated;
표현하고자 하는 의미는 핸드폰 인증 번호(코드) 인데 `AuthPhoneNumber` 라는 클래스 이름이 부적절해보입니다. `Code` 라는 단어가 들어가면 좋을거 같아요.

또한 `isValidated` 유효한지의 여부가 아닌 인증 여부를 의미하는 `authenticated` 가 필드명으로 더 적절해 보입니다. 앞고로 `boolean` 필드에서 `is` prefix 는 다른 일반 필드의 `get` 과 같은 의미로 필드명 자체에는 포함 하지 않는것이 일반적입니다.

2023-04-12 07:09 UTC, ndy2 commented on src/main/java/com/avalon/avalonchat/domain/auth/domain/AuthPhoneNumber.java
> +	}
생성자에서 기본적인 checkNotNull 정도는 검증해주면 좋을거 같아요.

2023-04-12 07:09 UTC, ndy2 commented on src/main/java/com/avalon/avalonchat/domain/auth/dto/AuthPhoneNumberRequest.java
> +}
DTO 를 Nested Class 로 작성하는 것도 좋은 방법이지만 현재 저희 코드 컨벤션과는 맞지 않는거 같아요.
`user.dto` 패키지를 확인해주세요.

2023-04-12 07:09 UTC, ndy2 commented on src/main/java/com/avalon/avalonchat/domain/auth/service/AuthServiceImpl.java
> +	}
Random 객체가 매 요청마다 생성되는 부분이 불필요한것 같습니다.
aphache commons 가 의존성에 추가되어 있으니까 `아파치.커먼스.RandomStringUtils.randomNumeric(100000, 999999)` 를 활용하면 좋을거 같네요.

2023-04-12 07:09 UTC, ndy2 commented on src/main/java/com/avalon/avalonchat/domain/auth/service/CoolSmsMessageService.java
> +			properties.getDomain());
이 DefaultMessageService 역시 message 를 전송할때마다 생성되는데 잘못된 방식같네요.

2023-04-12 07:09 UTC, ndy2 commented on src/main/java/com/avalon/avalonchat/domain/auth/service/CoolSmsMessageService.java
> +
CoolSms 라는 구체적인 기술이 domain 패키지에 있는것은 잘못된 방식같아요. infra 패키지의 도입이 필요한것 같습니다.

저희가 가이드 삼기로한 이 링크를 다시 확인해보시면 좋을거 같습니다. https://cheese10yun.github.io/spring-guide-directory/#-7

2023-04-12 07:09 UTC, ndy2 commented on src/test/java/com/avalon/avalonchat/domain/auth/service/AuthServiceImplTest.java
> +	private CoolSmsMessageService messageService;
주입 필드 클래스가 구체 클래스일 필요가 없을거 같아요.  인터페이스인 `MessageService` 는 어떨까요?

2023-04-12 07:09 UTC, ndy2 commented on src/test/java/com/avalon/avalonchat/domain/auth/service/CoolSmsMessageServiceTest.java
> +	private MessageService messageService;
반대로 이곳에는 테스트 대상인 CoolSmsMessageService 를 대상 클래스명과 필드명 `sut` (system under test) 를 통해  테스트의 의도를 더 잘 드러낼 수 있습니다.

추가로 이 테스트를 통해 실제 메시지가 날라가는것을 확인하고자 하는 의도는 이해했지만 굳이 매번 전체 테스트에서 실행 될 필요는 없을거 같아요. `@Disable` 를 달면 어떨까요?

2023-04-13 01:37 UTC, hgene0929 commented on src/test/java/com/avalon/avalonchat/domain/auth/service/AuthServiceImplTest.java
테스트는 코멘트 참고하여 자세한 서비스에 의존해야하는 CoolSmsMessageService는 sut를 주입받았고, 해당 구현체를 사용하는 AuthService는 인터페이스를 주입하였습니다.

이외의 수정은 테스트하는 원래코드가 변경됨에 따라 함께 수정된 것들입니당.

2023-04-13 01:37 UTC, hgene0929 commented on src/main/java/com/avalon/avalonchat/infra/message/configuration/CoolSmsConfiguration.java
매번 새롭게 DefaultMessageService 객체를 생성하는 것은 옳지 않기 때문에 스프링 빈을 따로 생성해주었습니다!

2023-04-13 01:37 UTC, hgene0929 commented on src/main/java/com/avalon/avalonchat/infra/message/CoolSmsMessageService.java
CoolSms 와 같은 코드는 코멘트에 남겨주신 구조를 참고하여 infra.message 에 따로 분리하였습니다

2023-04-13 01:37 UTC, hgene0929 commented on src/main/java/com/avalon/avalonchat/domain/auth/service/AuthServiceImpl.java
마찬가지로 매번 StringBuffer 객체를 생성하는 것은 옳지 않음으로 RandomStringUtils.randomNumeric()을 사용하였습니다

2023-04-13 01:37 UTC, hgene0929 commented on src/main/java/com/avalon/avalonchat/domain/auth/dto/AuthPhoneNumberCheckRequest.java
dto의 경우 코멘트에 첨언해주신대로 저희 프로젝트와는 맞지 않음으로 users.dto를 참고하여 변경하였습니당

2023-04-13 01:37 UTC, hgene0929 commented on src/main/java/com/avalon/avalonchat/domain/auth/controller/AuthController.java
엔티티명과 필드명(인증여부)은 조언해주신대로 수정해보았습니당

2023-04-13 07:01 UTC, ndy2 commented
RESTful 관련해서는 https://restfulapi.net/ 요 사이트가 잘 설명해주네요.

조금 현실적인 예제를 바탕으로한 이 세미나 영상 https://youtu.be/_SikP7FwZhY 도 추천드려요. 저는 이 세미나에서 추천하는 책 한권 이북으로 구매해서 한번 정리하는 방식으로 공부했습니다.

그런데 저 세미나를 포함에 많은 분들이 얘기 하시는 바에 따르면 현업에서도 그렇고 REST 라는게 이론과 현실에 괴리가 좀 많은거 같다고 합니다. `POST auth/phon_number`, `PATCH auth/phon_number` 가 각각 인증번호필드를 생성하고, authenticated 여부를 수정한다는 느낌에서 URI 엔드포인트를 그렇게 설계하신거 같은데 제 생각에 그러한 동작들은 너무 구현에 치중된 표현들 같기도 합니다.

다른 말로는 사실 클라이언트는 인증번호라는 리소스가 생성되고 내부적으로 인증 여부가 업데이트 쳐지는 동작에는 크게 관심이 없을거 같아요. 
그래서 제 생각에 이 엔드포인트 들은 인증번호 전송/확인이라고 하는 CRUD가 아닌 특별한 동작을 나타내는 `컨트롤러 리소스` 라고 생각해서 API Docs 와 같은 엔드포인트로 설계했었습니다.

Rest 에서 이야기하는 여러 리소스 종류는 위 링크 및 여러 자료 참고하시면 쉽게 찾을수 있을겁니다

2023-04-13 14:48 UTC, ndy2 approved these changes
👍

2023-04-13 14:55 UTC, ndy2 commented
번외로... @YOONSUNGHYEON 님의 오늘 PR 에서와 마찬가지로 제 원대한 꿈을 말씀드리자면

개인적으로 장기적으로 보았을때 아래의 변경을 해보고 싶네요. 
익숙하지 않은 주제라면 이번 PR 에서 굳이 하실필요는 없다고 생각됩니다. (저도 안 익숙함;; 찾아봐야됨)

스프링 데이터 레디스를 통해 레디스를 key value 저장소로 이용하는 방식에는 두가지가 있습니다.
1. 리포지토리 상속 (지금 처럼)
2. RedisTemplate

제 의견에는 인증번호 시리즈와 리프레스 토큰 같은경우는 2번을 적용하고 싶고 채팅 메시지 같은경우는 1번을 적용하고 싶네요.
그 이유는... 제가 밀고있는 DDD 에서 리포지토리라는 용어가 가지는 의미가 있는데 그에 맞다고 생각되기 때문입니다.

2023-04-13 15:02 UTC, hgene0929 commented
넵 좋은 내용 공유 감사합니당 관려해서는 더 공부해볼게요!! 해당 내용 관련해서는 우선 이 pr은 머지하고, 프로필 수정 후에 공부한 내용을 바탕으로 수정해봐도 될까요!?🤓

2023-04-13 15:03 UTC, ndy2 commented
넵 당연히 저희 기준에따라 1개 이상의 approval 이 있으면 머지 아무나 하셔도 됩니다. 👍

2023-04-13 15:04 UTC, hgene0929 commented
호우:) 감사함당 관려해서는 학습 후에 수정해보겠습니당:)😎

2023-04-13 15:05 UTC, merged